### PR TITLE
Redo table layout.

### PR DESCRIPTION
**Pull request by anntzer**
## PR Summary

before:
old
after:
new

Closes https://github.com/matplotlib/mpl-third-party/issues/24.

### CODE REVIEW

**Comment by jklymak** [comment]
So I guess that depends on your screen but I prefer wider with more entries per vertical space.   But I'd be fine w either

**Comment by anntzer** [comment]
The point is not so much about screen width (I also prefer just wider things), but about the fact that the pypi badges (for example) get sized slightly differently on each row in the old example, which is a bit jarring.

**Comment by jklymak** [comment]
I guess I'd made those columns fixed width but they could just be changed to expanding?

**Comment by anntzer** [comment]
I don't actually have a strong opinion on the best way to prevent the badge resizing issue; breaking over two lines was just the first thing I could think of.

**Comment by QuLogic** [comment]
The badges are sized differently because of the `img { max-width: 100% }` in `basic.css`; the logos are all the same height, but different widths, so they get scaled differently since a column only has one width. This rule should probably be made a bit more specific.

**Comment by QuLogic** [comment]
You could also remove `?style=social` from the GitHub badge, to make it the same style as the others.

**Comment by jklymak** [comment]
I guess I'm not sure what the version name gets us anyway:

nobadge

**Comment by jklymak** [comment]
See #40 for another alternative, with the added benefit of using static badges.

**Comment by jklymak** [comment]
I'll close in lieu of #40

**Pull request closed without merging**
