### PR TITLE
Add mpl_chord_diagram

### PR DESCRIPTION
**Pull request by tfardet**
Python package to draw chord diagrams in matplotlib: https://codeberg.org/tfardet/mpl_chord_diagram

### CODE REVIEW

**Comment by tfardet** [comment]
Ah, I see, this requires #100 before it can be merged (there is technically a GitHub repo but I don't want to advertise it because it's just there due to historical reasons and I'm not maintaining it anymore and I'm actually considering deleting it)

**Comment by tfardet** [comment]
@timhoffm @QuLogic sorry, it turns out I missed the pre-commit check for ``repo`` in #156... is it OK if I fix it here or should I reopen another PR for it?

**Comment by QuLogic** [comment]
It's probably fine, though perhaps rebase instead of merge?

**Comment by tfardet** [comment]
@QuLogic done :)

**Comment by oscargus** [comment]
Thanks @tfardet!

**Pull request merged**
