### PR TITLE
ENH: layout with fixed badges

### PR DESCRIPTION
**Pull request by jklymak**
## PR Summary

Version of layout with static fixed badges.

### CODE REVIEW

**Comment by jklymak** [comment]
New version: https://111-358923886-gh.circle-artifacts.com/0/docs/build/html/index.html

**Comment by QuLogic** [comment]
Those are entirely too small now:
image

**Comment by jklymak** [comment]
Huh, thats bizarre.  I can get them to look normal or small by changing the font zooming.  By default they look good, but of course we should fix them to always look good.

**Comment by QuLogic** [comment]
If you don't want to change the Sphinx CSS, you can override it for just the table with something like `td img { max-width: none; }` in wherever our custom CSS goes.

**Comment by jklymak** [comment]
I think setting the badge height to 1.4em will work.

**Comment by jklymak** [comment]
BTW, we could/should use a custom class here?  I'm a bit of an ignoramus about how to properly style html/css

**Comment by jklymak** [comment]
https://112-358923886-gh.circle-artifacts.com/0/docs/build/html/index.html works for me, except for the very smallest font zoom....

**Comment by QuLogic** [comment]
Are you viewing at default zoom?
image

**Comment by jklymak** [comment]
yes,  but I can get your effect if I make my viewport that narrow.

**Comment by jklymak** [comment]
Better? https://112-358923886-gh.circle-artifacts.com/0/docs/build/html/index.html

**Comment by jklymak** [comment]
... no not really better, you can still get the badges pretty small.

**Comment by jklymak** [comment]
The fundamental problem here is that these are 8 different tables, and its very hard to make different tables look the same as each other, at least given my minimal html skills.  

A solution would be to make them one table, and have the headings as col-span table entries.  The disadvantage is that we would lose the table of contents. 

Or we could live with the different tables being different widths.

**Comment by jklymak** [comment]
I think this version is pretty good.  But no table of contents...

**Review by anntzer — APPROVED** [review]

**Comment by jklymak** [comment]
@QuLogic  you still had a concern about this?

**Comment by QuLogic** [comment]
Yes, if you can figure out where to put CSS, the style from https://github.com/matplotlib/mpl-third-party/pull/40#issuecomment-824440465 should be added to fix the size of the badges.

**Comment by jklymak** [comment]
Latest push these are just hardcoded in.  This makes the badges not change size, which is probably better.

**Pull request merged**
